spring:
  application:
    name: gestion
    
info:
  component: Microservicios
  
server:
  port: 0

eureka:
  instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${ramdom.value}}}
  
cloud:
  services:
    registrationMethod: route
    