spring:
  application:
    name: servicesdata
    
info:
  component: Microservicios
  
server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${ramdom.value}}}
  
cloud:
  services:
    registrationMethod: route